dist: precise
language: minimal
sudo: false
install: ruby --version
script:
    - gem install dpl
    - "dpl --provider=elasticbeanstalk || true"
    - "head -n 1000 $(find ~ -name Gemfile.lock)"
notifications:
    email: false
