language: cpp
sudo: true
dist: trusty
# Add-ons: specify apt packages for Linux
addons:
  apt: 
   packages:
      - couchdb
before_install:
   - true
install:
    - "curl http://127.0.0.1:5984/ || true"
script:
    - true
notifications:
    email: false
