dist: precise
language: minimal
sudo: false
install: ruby --version
script:
    - git clone https://github.com/travis-ci/dpl.git
    - cd dpl
    - gem build dpl.gemspec
    - gem install dpl-1.8.28.gem
    - "dpl --provider=elasticbeanstalk || true"
    - "head -n 1000 $(find ~ -name Gemfile.lock)"
notifications:
    email: false
