dist: precise
language: python
python: 2.7
matrix:
    include:
        - env: image=sudo
          sudo: required
        - env: image=container
          sudo: false
install: true
script: openssl version
notifications:
    email: false
