language: ruby
dist: trusty
sudo: false
matrix:
    include:
        - group: edge
        - group: stable
        - group: beta
services:
    - mysql
install:
    - true
script:
    - "mysql -uroot -e 'show variables like \"%version%\";' || true"
notifications:
    email: false

