sudo: false
language: ruby
dist: trusty
script:
    - awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' $a
    - awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' "$a"
    - travis_wait awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' "$a"
install: true
env:
    global:
        a="one two three"
notifications:
    email: false
