sudo: false
dist: trusty
group: beta 
install: true
script: 
    - "ps aux | grep '[m]ysql' || true"
    - "mysql -uroot -e 'select now()' || true"
    - "mysql -utravis -e 'select now()' || true"
notifications:
    email: false

