sudo: false
language: ruby
dist: trusty
script: hostname
install: true
matrix:
    include:
        - env: group=stable
          group: stable
        - env: group=edge
          group: edge
        - env: group=beta
          group: beta
notifications:
    email: false
