language: ruby
addons:
    postgresql: "9.5"
services:
    - postgresql
install:
    - "PAGER=cat psql -U postgres -c 'select * from version();' || true"
    - "PAGER=cat psql -U travis -c 'select * from version();' || true"
matrix:
    include:
        - env: image="precise sudo stable"
          sudo: required
          dist: precise
          group: stable
        - env: image="precise sudo edge"
          sudo: required
          dist: precise
          group: edge
        - env: image="precise container stable"
          sudo: false
          dist: precise
          group: stable
        - env: image="precise container edge"
          sudo: false
          dist: precise
          group: edge
script:
    - true
notifications:
    email: false

