language: c
install: true
dist: precise
sudo: required
script:
    - curl -I http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/binary-i386/Packages
notifications:
    email: false
env:
    global:
        - image="sudo trusty stable"
        - PAGER=cat
group: stable
