language: c
dist: trusty
sudo: required
matrix:
    include:
        - env: group=stable
          group: stable
        - env: group=deprecated
          group: deprecated
install: true
script:
    - mysql -uroot -e 'SHOW VARIABLES WHERE Variable_Name LIKE "%dir"'
