language: generic

sudo: false

env:
    matrix:
        - fail=yes
        - fail=no

install:
  - true

before_script:
  - "[[ $fail = yes ]] && false || true"

script:
    - true

after_script:
    - echo Afterscript runs with fail $fail

after_failure:
    - echo Afterscript runs with fail $fail

notifications:
  email: false

