language: php
sudo: required
dist: trusty
group: edge
matrix:
    include:
        - env: try="addons"
          addons:
            apt:
              packages:
                - mysql-client-5.6
                - mysql-server-5.6
                - mysql-core-5.6
        - env: try="no addon"

install:
    - true
script:
    - "mysql -uroot -e 'show variables like \"%version%\";' || true"
    - "mysql -uroot -h localhost -e 'show variables like \"%version%\";' || true"
    - "mysql -uroot -h 127.0.0.1 -e 'show variables like \"%version%\";' || true"
notifications:
    email: false

