language: php
sudo: required
dist: trusty
group: stable
php: 5.6
addons:
    apt:
        packages:
            - mysql-server
            - mysql-client
install: true
script:
    - php -i
    - "sudo grep -r 'sock' /etc/my* /usr/bin/mysql_config 2>/dev/null"
    - sudo lsof -p $(pgrep mysql) | grep sock
notifications:
    email: false

