language: java
jdk: oraclejdk8
install:
    - declare -f jdk_switcher
    - print_home_of_oraclejdk8
    - echo ORACLEJDK8_JAVA_HOME $ORACLEJDK8_JAVA_HOME
    - echo ORACLEJDK8_UJA_ALIAS $ORACLEJDK8_UJA_ALIAS
    - head -n 1000 /etc/profile /etc/profile.d/*sh
    - grep -C5 --color=always JAVA /etc/profile /etc/profile.d/*.sh /etc/bash.bashrc ~/.*

script:
    - "java -version || true"
    - ls -l /usr/lib/jvm
    - source /opt/jdk_switcher/jdk_switcher.sh
    - "jdk_switcher use oraclejdk8 || true"
    - "java -version || true"
    - print_home_of_oraclejdk8
    - echo ORACLEJDK8_JAVA_HOME $ORACLEJDK8_JAVA_HOME
    - echo ORACLEJDK8_UJA_ALIAS $ORACLEJDK8_UJA_ALIAS
    - declare -f jdk_switcher
env: "image=sudo trusty edge"
sudo: required
dist: trusty
group: edge
notifications:
    email: false

