sudo: false
language: ruby
matrix:
    include:
        - env: dist=precise
          dist: precise
        - env: dist=trusty
          dist: trusty
group: stable
install: true
script:
    - df -h
notifications:
    email: false
