language: ruby
group: stable
os: ubuntu
dist: precise
sudo: true
install: true
script:
    - "false"
after_failure:
    - "awk 'BEGIN{while(1)print \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"}'"


