language: android
matrix:
    include:
        - env: dist=trusty
          dist: trusty
        - env: dist=precise
          dist: precise
sudo: true
install:
    - true
script:
    - "android list sdk --no-ui --all --extended"
notifications:
    email: false

