language: php
sudo: false
dist: trusty
group: edge
install:
    - true
script:
    - "mysql -uroot -e 'show variables like \"%version%\";' || true"
    - "mysql -uroot -h localhost -e 'show variables like \"%version%\";' || true"
    - "mysql -uroot -h 127.0.0.1 -e 'show variables like \"%version%\";' || true"
notifications:
    email: false

