sudo: false
cache:
    directories:
        - /home/travis/virtualenv/python2.7.9
dist: precise
language: python
python: "2.7"
install:
    - pip install i3ipc
    - echo commit 3
script:
    - echo $TRAVIS_TAG
notifications:
    email: false
