language: c
install: true
dist: trusty
sudo: required
script: 
    - "sudo service mysql restart || true"
    - "sudo service mysql-5.6 restart || true"
notifications:
    email: false
env: image="sudo trusty edge"
group: stable
