language: r
sudo: false
dist: precise
os: linux
install: true
script:
    - cat ~/.bashrc
    - "echo \"echo reading this!\">>~/.bashrc"
    - "echo \"PATH=/abc:$PATH\">>~/.bashrc"
    - source ~/.bashrc
    - echo $PATH
notifications:
    email: false

