language: ruby
matrix:
   include:
     - os: linux
       dist: trusty
       sudo: required
     - os: osx
       osx_image: xcode8
services:
    - postgresql
addons:
    postgresql: "9.5"
install:
    - psql -U postgres -c "select * from version()"
script:
    - true
