language: c
dist: precise
sudo: required
install: true
script:
    - mysql -uroot -e 'SHOW VARIABLES WHERE Variable_Name LIKE "%dir"'
    - mysql -uroot -e 'SHOW VARIABLES WHERE Variable_Name LIKE "%vers%"'
    - df -h
    - mount
