language: cpp
sudo: false
compiler:
    - gcc
os:
    - linux
# Add-ons: specify apt packages for Linux
addons:
  apt: 
   sources:
      - boost-latest
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8
      - g++-4.8
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
      - libboost1.55-all-dev
      - libgif-dev
      - libtiff4-dev
      - libopenjpeg-dev
      - libwebp-dev
      - ffmpeg
      - freetype6-dev
      - libjpeg-turbo8-dev
before_install:
   - true
install:
    - true
script:
    - true
notifications:
    email: false
