sudo: true
dist: trusty
language: ruby
install:
    - true
services:
    - mysql
script:
    - "mysql --protocol=TCP --host=localhost --user root -e \"CREATE USER 'nice'@'localhost' IDENTIFIED BY 'nice'\" || true"
notifications:
    email: false
