sudo: true
dist: trusty
language: ruby
before_install:
   - sudo add-apt-repository -y ppa:ondrej/mysql-5.7
   - sudo apt-get update -qq
   - sudo apt-get install mysql-server-5.7 mysql-client-5.7
install:
    - true
script:
    - "mysql --protocol=TCP --host=localhost --user root -e \"CREATE USER 'nice'@'localhost' IDENTIFIED BY 'nice'\" || true"
    - "mysql --user nice --password nice 'select * from CURTIME()'"
notifications:
    email: false
