language: __connie__

sudo: true

dist: trusty

addons:
  apt:
    packages:
    - postgresql-9.4

before_script:
  - "psql -c 'select * from version()' || true"

script:
    - true

install: true

notifications:
  email: false

