language: php
sudo: required
dist: trusty
matrix:
    include:
        - env: image="group: edge"
          group: edge
        - env: image="group: stable"
          group: stable
php: 5.6
install: true
script:
    - php -i
    - "sudo grep -r 'sock' /etc/my* /usr/bin/mysql_config 2>/dev/null"
    - sudo lsof -p $(pgrep mysql) | grep sock
notifications:
    email: false

