language: php
dist: trusty
sudo: required
group: edge
install:
    - "composer global require drush/drush:7.*"
    - export PATH=~"/.composer/vendor/bin/drush:$PATH"
    - drush dl drupal --drupal-project-rename=example
    - cd example
script:
    - "drush site-install standard --db-url='mysql://root@localhost/exampledb'  --yes --site-name=Example || true"
    - "drush site-install standard --db-url='mysql://root:@localhost/exampledb'  --yes --site-name=Example || true"
notifications:
    email: false

