language: __sugilite__
sudo: true
dist: trusty
group: edge
# Add-ons: specify apt packages for Linux
addons:
  apt: 
    packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
before_install:
   - true
install:
    - true
script:
    - true
notifications:
    email: false
