language: c
install: true
dist: trusty
sudo: required
script: 
    - "mysql -u root -e \"CREATE USER 'rsyslog'@'localhost' IDENTIFIED BY 'testbench';\" || true"
matrix:
    include:
        - env: image=deprecated
          group: deprecated
        - env: image=stable
          group: stable
        - env: image=edge
          group: edge
        - env: image=stable-20161201
          group: stable-20161201
notifications:
    email: false
