language: php
php: "7.0"
matrix:
    include:
        - env: image="container trusty stable"
          dist: trusty
          group: stable
          sudo: required
        - env: image="container trusty beta"
          dist: trusty
          sudo: false
          group: beta
        - env: image="container trusty edge"
          dist: trusty
          sudo: false
          group: edge
install: true
script: 
    - "ps aux | grep '[m]ysql' || true"
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%sock%\";' || true"
    - "mysql -uroot -e 'SHOW VARIABLES' || true"
notifications:
    email: false
