sudo: false
dist: trusty
group: stable
language: php
php: 5.6
install: true
script:
    - grep -rI 'mysqld.sock' ~
    - mysql -h 127.0.0.1 -e "show variables like '%socket%'"
notifications:
    email: false
