language: c
install: true
dist: trusty
sudo: true
script: 
    - "mysql -u root -e \"CREATE USER 'rsyslog'@'localhost' IDENTIFIED BY 'testbench';\" || true"
addons:
    mariadb: '10.1'
notifications:
    email: false
