language: ruby
matrix:
   include:
   - os: linux
     dist: trusty
     sudo: required
   - os: osx
     osx_image: xcode8
services:
  - postgresql
addons:
   postgresql: "9.5"
before_install:
  - "[[ $TRAVIS_OS_NAME = osx ]] && pg_ctl -D /usr/local/var/postgres start"
script:
    - PAGER=cat psql -U postgres -c "select * from version()"
