language: php
sudo: true
dist: trusty
group: edge
php: 5.6
install:
  - sudo sed -i 's/\[mysqld\]/[mysqld]\nmax_connections = 500/' /etc/mysql-5.6/my.cnf\
  - sudo sync
  - sudo service mysql restart

script:
    - mysql -uroot 'show variables like "%connection%";'
notifications:
    email: false

