language: sh
group: stable
os: ubuntu
sudo: required
matrix:
    include:
        - stack: sugilite
          env: stack=sugilite
        - stack: amethyst
          env: stack=amethyst
        - stack: garnet
          env: stack=garnet
        - stack: connie
          env: stack=connie

install:
    - df -hi && df -h && echo $stack
script: true


