language: c
install: true
dist: trusty
sudo: required
script: 
    - "java -version || true"
    - "jdk_switcher use oraclejdk8"
    - "java -version || true"
    - "sudo service mysql restart || true"
    - "sudo service mysql-5.6 restart || true"
notifications:
    email: false
env: image="sudo trusty stable"
group: stable
