sudo: true
dist: precise
language: __garnet__
python: "2.7"
install:
    - echo $TRAVIS_PYTHON_VERSION
script:
    - "echo 'echo $TRAVIS_PYTHON_VERSION' > script.sh"
    - bash script.sh
notifications:
    email: false
