sudo: false
dist: precise
language: python
before_install:
   - true
install:
    - true
script:
    - true
notifications:
    email: false

before_deploy:
    - "echo true; true"
deploy:
    skip_cleanup: true
    provider: script
    script: "echo false; false"

after_deploy:
    - "echo true; true"
