language: java
sudo: required
dist: trusty
group: edge
os: linux
jdk:
    - oraclejdk8
install: true
script:
    - "java -version || true"
    - "javac -version || true"
    - echo $JAVA_HOME
    - cat ~/.jdk_switcher_rc
notifications:
    email: false

