language: c
install: true
dist: trusty
sudo: required
services:
    - postgresql
script: 
    - "psql -c 'select * from version();' || true"
    - "psql -c 'create database testdb;' -U postgres || true"
    - "psql -c 'CREATE EXTENSION postgis;' -U postgres -d testdb || true"
    - "psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d testdb || true"
notifications:
    email: false
env:
    global:
        - image="sudo trusty stable" 
        - PAGER=cat
group: stable
