language: php
php: "7.0"
notifications:
    email: false
matrix:
    include:
        - env: image="sudo trusty stable"
          dist: trusty
          group: stable
          sudo: required
        - env: image="sudo container trusty defasult mysql"
          dist: trusty
          group: stable
          sudo: false
        - env: image="sudo container trusty apt mysql"
          dist: trusty
          group: stable
          sudo: false
          addons:
              apt:
                  packages:
                      - mysql-server-5.6
                      - mysql-client-core-5.6
                      - mysql-client-5.6
install: true
script: 
    - "ps aux | grep '[m]ysql' || true"
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%sock%\";' || true"
    - "mysql -uroot -e 'SHOW VARIABLES' || true"
notifications:
    email: false
