sudo: required
dist: trusty
install: true
addons:
    apt:
        packages:
            - mysql-server
            - mysql-client
services:
    - mysql
script: 
    - "ps aux | grep '[m]ysql' || true"
    - "mysql -uroot -e 'select now()' || true"
    - "mysql -utravis -e 'select now()' || true"
notifications:
    email: false

