language: go
install: true
dist: trusty
sudo: true
script: 
    - netstat -natpu
    - "sudo apt-get install mongodb-server mongodb-clients -y"
    - sleep 10
    - netstat -natpu
    - mkdir -p /tmp/mongdb/rs0-0
    - "sudo service mongodb stop || true"
    - "sudo service mongod stop || true"
    - mongod --port 27017 --dbpath '/tmp/mongdb/rs0-0' --replSet rs0 --smallfiles --nohttpinterface --oplogSize 16 &
    - sleep 5
    - netstat -natpu

notifications:
    email: false
