language: ruby
os: linux
dist: trusty
sudo: required
services:
    - postgresql
addons:
    postgresql: "9.5"
install:
    - psql --version
    - echo $PAGER
    - "head ~/.psqlrc || true"
script:
    - psql -U postgres -c "select * from version()"
