language: ruby
group: stable
sudo: false
cache:
    directories:
        - cachedir
script:
    - touch -d 20160704 cachedir/oldfile
    - touch cachedir/currentfile
    - ls -Rla
install:
    - uname -a
