language: java
jdk: oraclejdk8
install:
    - declare -f jdk_switcher
script:
    - java -version
    - ls -l /usr/lib/jvm
    - source /opt/jdk_switcher/jdk_switcher.sh
    - "jdk_switcher use oraclejdk8 || true"
    - "java -version || true"
    - declare -f jdk_switcher
env: "image=sudo trusty edge"
sudo: required
dist: trusty
group: edge
notifications:
    email: false

