language: c
jdk: oraclejdk8
install: true
dist: trusty
sudo: required
script: 
    - "java -version || true"
    - "javac --version || true"
    - jdk_switcher use oraclejdk8
    - "java -version || true"
    - "javac --version || true"
notifications:
    email: false
env: image="sudo trusty edge"
group: edge
