language: python
python: 3.5
sudo: true
dist: trusty
group: edge
addons:
    postgresql: "9.6"
services:
    - postgresql
install:
    - "psql -U postgres -c 'select * from version();' || true"
    - "psql -U travis -c 'select * from version();' || true"
script:
    - true
notifications:
    email: false

