language: java
jdk: oraclejdk8
install: true
script:
    - java -version
    - ls -l /usr/lib/jvm
    - "head -n 1000 /etc/default/jdk-switcher \"${HOME}/.jdk_switcherrc\" \"${JDK_SWITCHER_CONFIG}\" || true"
    - "jdk_switcher use oraclejdk8 || true"
    - "java -version || true"
    - sudo rm -rf /usr/lib/jvm/default-java
    - "jdk_switcher use oraclejdk8 || true"
    - "java -version || true"
env: "image=sudo trusty edge"
sudo: required
dist: trusty
group: edge
notifications:
    email: false

