sudo: false
language: ruby
dist: precise
group: stable
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - firefox
    - sleep 3
script:
    - pstree -ap
    - sleep 3
    - echo nothing to do, exiting
notifications:
    email: false
