language: generic

sudo: false

env:
    matrix:
        - pass=yes
        - pass=no

install:
  - true

before_script:
  - "[[ $pass = yes ]] && true || false"

script:
    - echo "script runs"

after_script:
    - echo Afterscript runs with fail $fail

after_failure:
    - echo Afterscript runs with fail $fail

notifications:
  email: false

