sudo: required
dist: trusty
install: true
services:
    - mysql
script: 
    - "ps aux | grep '[m]ysql' || true"
    - "mysql -uroot -e 'select now()' || true"
    - "mysql -utravis -e 'select now()' || true"
notifications:
    email: false

