language: php
php: "5.6"
sudo: false
dist: trusty
install: true
script: 
    - "ps aux | grep '[m]ysql' || true"
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
    - "mysql -utravis -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
    - "mysql -uroot -e 'SHOW databases;' || true"
notifications:
    email: false
