language: __sugilite__

sudo: true

dist: trusty

services: 
    - postgresql

addons:
    postgresql: "9.4"

before_script:
  - true

script:
    - true

install: true

notifications:
  email: false

