language: ruby
#python: '2.7'
#group: stable
matrix:
    include:
        - osx_image: "xcode8"
          env: image=xcode8
        - osx_image: "beta-xcode6.3"
          env: image=beta-xcode6.3
        - sudo: required
          dist: trusty
        - sudo: required
          dist: precise
        - sudo: false

services:
    - cassandra
install:
    - echo $image
    - cassandra -v || true
script: true


