sudo: false
dist: precise
language: python
before_install:
   - true
install:
    - true
script:
    - true
notifications:
    email: false

before_deploy:
    - "true"
deploy:
    skip_cleanup: true
    provider: script
    script: "false"

after_deploy:
    - "true"
