language: php
php:
    - '7.1'
    - 'nightly'
install: true
dist: precise
sudo: required
script: 
    - php --version
notifications:
    email: false
env:
    global:
        - image="sudo trusty stable" 
        - PAGER=cat
group: stable
