sudo: false
cache:
    directories:
        - /home/travis/virtualenv/python2.7
dist: precise
language: python
python: "2.7"
install:
    - pip install i3ipc
script: true
notifications:
    email: false
