language: php
sudo: true
dist: trusty
group: beta
addons:
    apt:
        sources:
          - deb http://archive.ubuntu.com/ubuntu/ trusty multiverse
          - deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse
          - deb http://archive.ubuntu.com/ubuntu/ trusty universe
          - deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe
        packages:
          - mysql-server-5.6
          - mysql-client-5.6
          - mysql-client-core-5.6
install:
    - true
services:
    - mysql
script:
    - "mysql -c 'select now()' || true"
notifications:
    email: false

