language: ruby
group: stable
sudo: false
cache:
    - pip: true
    - directories:
        - cachedir
script:
    - pwd
    - echo $TRAVIS_BUILD_DIR
    - ls -lRa
    - touch -d 20160704 cachedir/oldfile
    - touch cachedir/currentfile
    - ls -Rla
install:
    - uname -a
