language: c
install: true
dist: trusty
sudo: required
script: 
    - "java -version || true"
    - "javac --version || true"
    - jdk_switcher use oraclejdk8
    - "java -version || true"
    - "javac --version || true"
notifications:
    email: false
matrix:
    include:
        - env: image="sudo trusty stable"
          group: stable
        - env: image="sudo trusty deprecated"
          group: deprecated
          addons:
              apt:
                  packages:
                      - mysql-client-5.6
                      - mysql-server-5.6
                      - mysql-client-core-5.6
        - env: image="sudo trusty edge"
          group: edge
