language: c
install: true
dist: trusty
sudo: false
addons:
    postgresql: "9.6"
services:
    - postgresql
script: 
    - "psql -c 'select * from version();' -Upostgres || true"
notifications:
    email: false
env:
    global:
        - image="sudo trusty stable" 
        - PAGER=cat
group: stable
