language: c
install: true
dist: trusty
sudo: false
script: 
    - "mysql -u root -e \"CREATE USER 'rsyslog'@'localhost' IDENTIFIED BY 'testbench';\" || true"
addons:
    apt:
        packages:
            - mysql-server-5.7
            - mysql-client-5.7
            - mysql-client-core-5.7
notifications:
    email: false
