language: node_js
sudo: true
node_js:
- "4"
env:
- CXX=g++-4.8
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
before_install:
- echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
- "echo \"deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse\" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.list"
- sudo apt-get update
- sudo apt-get install -y --force-yes mongodb-org=3.2.8 mongodb-org-server=3.2.8 mongodb-org-shell=3.2.8 mongodb-org-mongos=3.2.8 mongodb-org-tools=3.2.8
- sleep 15
- mongo --version

