language: ruby
install: true
dist: trusty
sudo: required
script: 
    - "ps aux | grep '[m]ysql' || true"
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
    - "mysql -utravis -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
    - "mysql -uroot -e 'select host, user, password from mysql.user;' || true"
notifications:
    email: false
matrix:
    include:
        - env: image="sudo trusty stable"
          group: stable
        - env: image="sudo trusty deprecated"
          group: deprecated
          addons:
              apt:
                  packages:
                      - mysql-client-5.6
                      - mysql-server-5.6
                      - mysql-core-5.6
        - env: image="sudo trusty edge"
          group: edge
