language: c
install: true
dist: trusty
sudo: false
postgres: 9.6
services:
    - postgresql
script: 
    - sudo apt-get install -y $(apt-cache search postgis | awk '/^postgresql-9\.[2-6]-postgis-2.3/{printf " "$1}' )
    - "psql -c 'select * from version();' -Upostgres || true"
notifications:
    email: false
env:
    global:
        - image="sudo trusty stable" 
        - PAGER=cat
group: stable
